version: "2"

run:
  timeout: 5m

linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - contextcheck
    - copyloopvar
    - dupl
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - forbidigo
    - gocheckcompilerdirectives
    - gochecksumtype
    - gocritic
    - godot
    - gomoddirectives
    - gomodguard
    - gosec
    - gosmopolitan
    - govet
    - importas
    - ineffassign
    - loggercheck
    - makezero
    - misspell
    - musttag
    - nilerr
    - nilnesserr
    - noctx
    - prealloc
    - protogetter
    - reassign
    - recvcheck
    - revive
    - rowserrcheck
    - spancheck
    - staticcheck
    - testifylint
    - unparam
    - unused
    - whitespace

  settings:
    exhaustive:
      default-signifies-exhaustive: true

    forbidigo:
      forbid:
        - pattern: ^print.*$
        - pattern: ^fmt\.Print.*$

  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - std-error-handling
    rules:
      - linters:
          - testifylint
        text: require-error
      - linters:
          - dupl
          - errcheck
          - gosec
        path: _test\.go
      - linters:
          - revive
        path: _test\.go
        text: unused-parameter

formatters:
  enable:
    - gci
    - goimports

  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/hetznercloud)
        - prefix(gitlab.com/hetznercloud)

  exclusions:
    generated: lax
