{
 "title": "gitlab-runner",
 "tags": [
  "gitlab-runner",
  "generated"
 ],
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "job",
    "query": "label_values(gitlab_runner_version_info, job)"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Info",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "gitlab_runner_version_info{job=~\"${job}\"}"
    }
   ]
  },
  {
   "title": "Jobs running",
   "type": "timeseries",
   "description": "Number of running jobs.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum by (job) (\ngitlab_runner_jobs{job=~\"${job}\"}\n)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Jobs failed",
   "type": "timeseries",
   "description": "Number of failed jobs per failure reason.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "sum by (job, failure_reason) (\nincrease(gitlab_runner_failed_jobs_total{job=~\"${job}\"}[$__rate_interval])\n)",
     "legendFormat": "{{failure_reason}}"
    }
   ]
  },
  {
   "title": "Runner saturation",
   "type": "timeseries",
   "description": "Saturation of the runner job capacity.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (job) (gitlab_runner_jobs{job=~\"${job}\"})\n/\nsum by (job) (gitlab_runner_concurrent{job=~\"${job}\"})",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Error rate",
   "type": "timeseries",
   "description": "Rate of errors being logged.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "sum by (job, level) (\nincrease(gitlab_runner_errors_total{job=~\"${job}\"}[$__rate_interval])\n)",
     "legendFormat": "{{job}}: {{level}}"
    }
   ]
  },
  {
   "title": "Average job duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (job) (\nrate(gitlab_runner_job_duration_seconds_sum{job=~\"${job}\"}[$__rate_interval])\n/\nrate(gitlab_runner_job_duration_seconds_count{job=~\"${job}\"}[$__rate_interval])\n)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Average pending job duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (job) (\nrate(gitlab_runner_job_queue_duration_seconds_sum{job=~\"${job}\"}[$__rate_interval])\n/\nrate(gitlab_runner_job_queue_duration_seconds_count{job=~\"${job}\"}[$__rate_interval])\n)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Job duration histogram",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "sum by (le) (\nincrease(gitlab_runner_job_duration_seconds_bucket{job=~\"${job}\"}[$__rate_interval])\n)"
    }
   ]
  },
  {
   "title": "Pending job duration histogram",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "targets": [
    {
     "expr": "sum by (le) (\nincrease(gitlab_runner_job_queue_duration_seconds_bucket{job=~\"${job}\"}[$__rate_interval])\n)"
    }
   ]
  },
  { "title": "Autoscaling", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Taskscaler saturation",
   "type": "timeseries",
   "description": "Saturation of the instances job capacity (capacity per instance * max instances).",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (job) (fleeting_taskscaler_tasks{job=~\"${job}\", state!~\"idle|reserved\"})\n/\nsum by (job) (\nfleeting_provisioner_max_instances{job=~\"${job}\"}\n*\nfleeting_taskscaler_max_tasks_per_instance{job=~\"${job}\"}\n)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Fleeting saturation",
   "type": "timeseries",
   "description": "Saturation of the max instances limit.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (job) (fleeting_provisioner_instances{job=~\"${job}\", state=~\"running|deleting\"})\n/\nsum by (job) (fleeting_provisioner_max_instances{job=~\"${job}\"})",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Fleeting instance creation timing",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "sum by (le) (\nincrease(fleeting_provisioner_instance_creation_time_seconds_bucket{job=~\"${job}\"}[$__rate_interval])\n)"
    }
   ]
  },
  {
   "title": "Fleeting instance ready timing",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "targets": [
    {
     "expr": "sum by (le) (\nincrease(fleeting_taskscaler_task_instance_readiness_time_seconds_bucket{job=~\"${job}\"}[$__rate_interval])\n)"
    }
   ]
  },
  {
   "title": "Fleeting instance deletion timing",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "sum by (le) (\nincrease(fleeting_provisioner_instance_deletion_time_seconds_bucket{job=~\"${job}\"}[$__rate_interval])\n)"
    }
   ]
  },
  {
   "title": "Fleeting instance life duration",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "targets": [
    {
     "expr": "sum by (le) (\nincrease(fleeting_provisioner_instance_life_duration_seconds_bucket{job=~\"${job}\"}[$__rate_interval])\n)"
    }
   ]
  },
  { "title": "HTTP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 } },
  {
   "title": "Total number of GitLab API requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
   "targets": [
    {
     "expr": "sum by (endpoint, status) (\nrate(gitlab_runner_api_request_statuses_total{job=~\"${job}\",}[$__rate_interval])\n)",
     "legendFormat": "{{endpoint}}: {{status}}"
    }
   ]
  }
 ]
}